
package restaurant.management.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.8
 * Sun Apr 14 15:01:32 CEST 2024
 * Generated source version: 3.5.8
 */

@XmlRootElement(name = "addRestaurant", namespace = "http://soap.management.restaurant/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addRestaurant", namespace = "http://soap.management.restaurant/")

public class AddRestaurant {

    @XmlElement(name = "restaurant")
    private restaurant.management.soap.Restaurant restaurant;

    public restaurant.management.soap.Restaurant getRestaurant() {
        return this.restaurant;
    }

    public void setRestaurant(restaurant.management.soap.Restaurant newRestaurant)  {
        this.restaurant = newRestaurant;
    }

}

